Feat: 우선은 기능만 만들어보기
Error "Uncaught (in promise) undefined 3 file.js:339:13
Uncaught (in promise) undefined 2 file.js:339:13
Error running bootstrap method 'startup' on lyradortiz913@gmail.com
ReadableStream is not defined addonassistant.js:25968
Uncaught (in promise) undefined
SyntaxError: JSON.parse: unexpected character at line 1 column 10 of the JSON data
4
DOMException: Could not get children of file(/Users/junheejang/Library/Application Support/Zotero/Crash Reports/events) because it does not exist CrashManager.sys.mjs:663:17
    _getUnprocessedEventsFiles resource://gre/modules/CrashManager.sys.mjs:663
    _getUnprocessedEventsFiles resource://gre/modules/CrashManager.sys.mjs:666
    _aggregatePromise resource://gre/modules/CrashManager.sys.mjs:333
    aggregateEventsFiles resource://gre/modules/CrashManager.sys.mjs:400
    runMaintenanceTasks resource://gre/modules/CrashManager.sys.mjs:423"

    수정할 것!